// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaResource = `-- name: CreateMediaResource :one
INSERT INTO media_resources (
    resource_key,
    password_hash,
    expires_at,
    salt
) VALUES (
    $1, $2, $3, $4
) RETURNING id, resource_key, password_hash, expires_at, viewed, created_at, salt
`

type CreateMediaResourceParams struct {
	ResourceKey  string           `json:"resource_key"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	Salt         []byte           `json:"salt"`
}

func (q *Queries) CreateMediaResource(ctx context.Context, arg CreateMediaResourceParams) (MediaResource, error) {
	row := q.db.QueryRow(ctx, createMediaResource,
		arg.ResourceKey,
		arg.PasswordHash,
		arg.ExpiresAt,
		arg.Salt,
	)
	var i MediaResource
	err := row.Scan(
		&i.ID,
		&i.ResourceKey,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.Viewed,
		&i.CreatedAt,
		&i.Salt,
	)
	return i, err
}

const deleteExpiredResources = `-- name: DeleteExpiredResources :exec
DELETE FROM media_resources
WHERE expires_at IS NOT NULL
AND expires_at <= NOW()
`

func (q *Queries) DeleteExpiredResources(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredResources)
	return err
}

const deleteMediaResource = `-- name: DeleteMediaResource :exec
DELETE FROM media_resources
WHERE resource_key = $1
`

func (q *Queries) DeleteMediaResource(ctx context.Context, resourceKey string) error {
	_, err := q.db.Exec(ctx, deleteMediaResource, resourceKey)
	return err
}

const getMediaResourceByKey = `-- name: GetMediaResourceByKey :one
SELECT id, resource_key, password_hash, expires_at, viewed, created_at, salt
FROM media_resources
WHERE resource_key = $1
AND (expires_at IS NULL OR expires_at > NOW())
AND viewed = FALSE
`

func (q *Queries) GetMediaResourceByKey(ctx context.Context, resourceKey string) (MediaResource, error) {
	row := q.db.QueryRow(ctx, getMediaResourceByKey, resourceKey)
	var i MediaResource
	err := row.Scan(
		&i.ID,
		&i.ResourceKey,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.Viewed,
		&i.CreatedAt,
		&i.Salt,
	)
	return i, err
}

const getMediaResourceForView = `-- name: GetMediaResourceForView :one
SELECT id, resource_key, password_hash, expires_at, viewed, created_at, salt
FROM media_resources
WHERE resource_key = $1
AND (expires_at IS NULL OR expires_at > NOW())
FOR UPDATE
`

func (q *Queries) GetMediaResourceForView(ctx context.Context, resourceKey string) (MediaResource, error) {
	row := q.db.QueryRow(ctx, getMediaResourceForView, resourceKey)
	var i MediaResource
	err := row.Scan(
		&i.ID,
		&i.ResourceKey,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.Viewed,
		&i.CreatedAt,
		&i.Salt,
	)
	return i, err
}

const markAsViewed = `-- name: MarkAsViewed :exec
UPDATE media_resources
SET viewed = TRUE
WHERE resource_key = $1
`

func (q *Queries) MarkAsViewed(ctx context.Context, resourceKey string) error {
	_, err := q.db.Exec(ctx, markAsViewed, resourceKey)
	return err
}
