// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaResource struct {
	ID           pgtype.UUID      `json:"id"`
	ResourceKey  string           `json:"resource_key"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	Viewed       pgtype.Bool      `json:"viewed"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Salt         []byte           `json:"salt"`
}
