// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckResourceAccess(ctx context.Context, resourceKey string) (CheckResourceAccessRow, error)
	VerifyPassword(ctx context.Context, resourceKey string) (pgtype.Text, error)
}

var _ Querier = (*Queries)(nil)
