// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkResourceAccess = `-- name: CheckResourceAccess :one
SELECT 
    id,
    resource_key,
    password_hash,
    expires_at,
    viewed,
    salt
FROM media_resources
WHERE resource_key = $1
AND (expires_at IS NULL OR expires_at > NOW())
`

type CheckResourceAccessRow struct {
	ID           pgtype.UUID      `json:"id"`
	ResourceKey  string           `json:"resource_key"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	Viewed       pgtype.Bool      `json:"viewed"`
	Salt         []byte           `json:"salt"`
}

func (q *Queries) CheckResourceAccess(ctx context.Context, resourceKey string) (CheckResourceAccessRow, error) {
	row := q.db.QueryRow(ctx, checkResourceAccess, resourceKey)
	var i CheckResourceAccessRow
	err := row.Scan(
		&i.ID,
		&i.ResourceKey,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.Viewed,
		&i.Salt,
	)
	return i, err
}

const verifyPassword = `-- name: VerifyPassword :one
SELECT password_hash FROM media_resources
WHERE resource_key = $1
`

func (q *Queries) VerifyPassword(ctx context.Context, resourceKey string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, verifyPassword, resourceKey)
	var password_hash pgtype.Text
	err := row.Scan(&password_hash)
	return password_hash, err
}
